# Generated by Django 5.1.7 on 2025-04-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_option_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.FloatField(help_text='Giá gốc của sản phẩm', null=True),
        ),
    ]
