# Generated by Django 5.1.7 on 2025-04-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_brand_slug_category_slug_option_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='img',
            field=models.TextField(blank=True, help_text='Danh sách URL hình ảnh', null=True),
        ),
    ]
