# Generated by Django 5.1.7 on 2025-04-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_option_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='quantity',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
