# Generated by Django 5.1.7 on 2025-04-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_review_product_review_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
