# Generated by Django 5.1.7 on 2025-04-19 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_review_option_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.option'),
        ),
    ]
