# Generated by Django 5.1.7 on 2025-04-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_review_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
