# Generated by Django 5.1.7 on 2025-04-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_review_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
