# Generated by Django 5.1.7 on 2025-04-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_review_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='featureHighlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='quality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
