# Generated by Django 5.1.7 on 2025-04-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_user_email_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Phần trăm giảm giá', max_digits=5, null=True),
        ),
    ]
