# Generated by Django 5.1.7 on 2025-04-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_order_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchased',
        ),
    ]
