# Generated by Django 5.1.7 on 2025-04-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đang xử lý'), ('shipping', 'Đang giao hàng'), ('shipped', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=50),
        ),
    ]
