# Generated by Django 5.1.7 on 2025-05-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_user_birthday'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user_option_review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='has_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Ngày tạo bản ghi', null=True),
        ),
    ]
