# Generated by Django 5.1.7 on 2025-05-18 08:10

import django.db.models.deletion
import myapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0030_remove_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='battery_and_charging',
        ),
        migrations.RemoveField(
            model_name='option',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='option',
            name='design_and_weight',
        ),
        migrations.RemoveField(
            model_name='option',
            name='display',
        ),
        migrations.RemoveField(
            model_name='option',
            name='front_camera',
        ),
        migrations.RemoveField(
            model_name='option',
            name='general_information',
        ),
        migrations.RemoveField(
            model_name='option',
            name='img',
        ),
        migrations.RemoveField(
            model_name='option',
            name='memory_and_storage',
        ),
        migrations.RemoveField(
            model_name='option',
            name='os_and_cpu',
        ),
        migrations.RemoveField(
            model_name='option',
            name='product_overview',
        ),
        migrations.RemoveField(
            model_name='option',
            name='promotion_description',
        ),
        migrations.RemoveField(
            model_name='option',
            name='promotion_end_date',
        ),
        migrations.RemoveField(
            model_name='option',
            name='promotion_start_date',
        ),
        migrations.RemoveField(
            model_name='option',
            name='rear_camera',
        ),
        migrations.RemoveField(
            model_name='option',
            name='utilities',
        ),
        migrations.RemoveField(
            model_name='option',
            name='warranty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.RemoveField(
            model_name='review',
            name='img',
        ),
        migrations.AddField(
            model_name='option',
            name='details',
            field=models.JSONField(blank=True, help_text='Thông tin chi tiết dạng JSON', null=True),
        ),
        migrations.CreateModel(
            name='OptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True,
                                          upload_to=myapp.upload_paths.ProcessingUploadPath.option_image_upload_path
                                          )),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                             to='myapp.option')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, help_text='Ảnh đại diện sản phẩm', null=True,
                                          upload_to=myapp.upload_paths.ProcessingUploadPath.product_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True,
                                          upload_to=myapp.upload_paths.ProcessingUploadPath.review_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files',
                                             to='myapp.review')),
            ],
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
