# Generated by Django 5.1.7 on 2025-05-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_option_battery_and_charging_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Giá gốc của sản phẩm', max_digits=20, null=True),
        ),
    ]
