# Generated by Django 5.1.7 on 2025-05-20 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_option_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='color',
        ),
        migrations.RemoveField(
            model_name='option',
            name='details',
        ),
        migrations.RemoveField(
            model_name='option',
            name='price',
        ),
        migrations.RemoveField(
            model_name='option',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='option',
            name='product',
            field=models.ForeignKey(help_text='Sản phẩm tương ứng', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='myapp.product'),
        ),
        migrations.CreateModel(
            name='OptionColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.option')),
            ],
        ),
        migrations.CreateModel(
            name='OptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.option')),
            ],
        ),
    ]
