# Generated by Django 5.1.7 on 2025-05-20 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_option_color_remove_option_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionimage',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.optioncolor'),
        ),
    ]
