# Generated by Django 5.1.7 on 2025-05-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_optionimage_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionimage',
            old_name='option',
            new_name='option_color',
        ),
    ]
