# Generated by Django 5.1.7 on 2025-05-20 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_rename_option_optionimage_option_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionimage',
            name='option_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.optioncolor'),
        ),
    ]
