# Generated by Django 5.1.7 on 2025-05-21 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_orderitem_option_orderitem_option_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='option',
        ),
        migrations.AddField(
            model_name='review',
            name='option_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.optioncolor'),
        ),
    ]
