# Generated by Django 5.1.7 on 2025-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_review_option_review_option_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='need_invoice',
            field=models.BooleanField(default=False, help_text='Có cần in hóa đơn không'),
        ),
    ]
