# Generated by Django 5.1.7 on 2025-05-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_product_status_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioncolor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='optiondetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='optionimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
