# Generated by Django 5.1.7 on 2025-05-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_optioncolor_is_active_optiondetail_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
