# Generated by Django 5.1.7 on 2025-05-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
