# Generated by Django 5.1.7 on 2025-05-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_ordercancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercancellation',
            name='note',
            field=models.TextField(blank=True, help_text='Ghi chú nội bộ thêm khi hủy đơn hàng', null=True),
        ),
    ]
